import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import test from 'node:test'
import { fileURLToPath } from 'node:url'
import { updateCargoPackageVersion, updatePackageLock } from '../scripts/release/version.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const repositoryUrl = 'git+https://github.com/jazelly/tokenless.git'
const nativePackages = [
  'tokenless-native-darwin-arm64',
  'tokenless-native-darwin-x64',
  'tokenless-native-linux-arm64',
  'tokenless-native-linux-x64',
  'tokenless-native-win32-arm64',
  'tokenless-native-win32-x64',
]

test('Changesets release configuration tracks only the public CLI', () => {
  const config = readJson('.changeset/config.json')
  const rootPackage = readJson('package.json')
  assert.equal(config.access, 'public')
  assert.equal(config.baseBranch, 'main')
  assert.deepEqual(config.ignore, [])
  assert.ok(rootPackage.devDependencies['@changesets/cli'])
  assert.equal(rootPackage.scripts.changeset, 'changeset')
  assert.equal(rootPackage.scripts['release:version'], 'node scripts/release/version.mjs')
})

test('npm manifests use the canonical repository and MIT license', () => {
  const rootPackage = readJson('package.json')
  const cliPackage = readJson('packages/cli/package.json')
  const legacyExtensionPackage = readJson('legacy/extension/package.json')
  assert.equal(rootPackage.license, 'MIT')
  assert.equal(cliPackage.repository.url, repositoryUrl)
  assert.equal(cliPackage.publishConfig.access, 'public')
  assert.equal(cliPackage.license, 'MIT')
  assert.equal(legacyExtensionPackage.license, 'MIT')
  assert.equal(fs.existsSync(path.join(root, 'packages/extension')), false)
  assert.deepEqual(Object.keys(cliPackage.optionalDependencies).sort(), nativePackages)

  for (const packageName of nativePackages) {
    const manifest = readJson(`packages/cli/npm/${packageName}/package.json`)
    assert.equal(manifest.repository.url, repositoryUrl)
    assert.equal(manifest.publishConfig.access, 'public')
    assert.equal(manifest.license, 'MIT')
  }
})

test('npm publishing is marker-gated, platform-complete, and cleans up in a second commit', () => {
  const prepare = readText('.github/workflows/prepare-npm-release.yml')
  const publish = readText('.github/workflows/publish-npm.yml')
  assert.match(prepare, /uses: changesets\/action@v1/)
  assert.match(prepare, /version: npm run release:version/)
  assert.match(prepare, /npm install --ignore-scripts/)
  assert.doesNotMatch(`${prepare}\n${publish}`, /npm ci/)
  assert.match(publish, /id-token: write/)
  assert.doesNotMatch(publish, /NPM_TOKEN|_authToken|Configure npm token fallback/)
  assert.match(publish, /\.changeset\/publish-pending\.json/)
  assert.match(publish, /needs: \[prepare, publish-native\]/)
  assert.match(publish, /rm package-lock\.json/)
  assert.match(publish, /npm install --package-lock-only --ignore-scripts/)
  assert.match(publish, /git rm \.changeset\/publish-pending\.json/)
  assert.match(publish, /git add package-lock\.json/)
  for (const [platform, arch] of [
    ['darwin', 'arm64'], ['darwin', 'x64'], ['linux', 'arm64'],
    ['linux', 'x64'], ['win32', 'arm64'], ['win32', 'x64'],
  ]) {
    assert.match(publish, new RegExp(`platform: ${platform}[\\s\\S]*arch: ${arch}`))
  }
})

test('npm publisher invokes Windows npm through a shell', () => {
  const publisher = readText('scripts/release/publish-package.mjs')
  assert.match(publisher, /shell: process\.platform === 'win32'/)
  assert.match(publisher, /path\.resolve\(packageDirectoryArgument\)/)
})

test('publish verification is a no-op without the tracked release marker', () => {
  const pending = path.join(root, '.changeset', 'publish-pending.json')
  assert.equal(fs.existsSync(pending), false)
  const result = spawnSync(process.execPath, ['scripts/release/verify-pending.mjs'], {
    cwd: root,
    encoding: 'utf8',
  })
  assert.equal(result.status, 0, result.stderr)
  assert.equal(result.stdout, 'publish=false\n')
})

test('release versioning updates only tokenless-daemon in Cargo manifests', (t) => {
  const fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'tokenless-release-cargo-'))
  t.after(() => fs.rmSync(fixture, { recursive: true, force: true }))
  const cargoToml = path.join(fixture, 'Cargo.toml')
  const cargoLock = path.join(fixture, 'Cargo.lock')

  fs.writeFileSync(cargoToml, `[package]
name = "tokenless-daemon"
version = "0.1.2"
edition = "2021"

[dependencies]
tokenless-helper = "0.1.2"
`)
  fs.writeFileSync(cargoLock, `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "ahash"
version = "0.8.12"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokenless-daemon"
version = "0.1.2"
dependencies = [
 "ahash",
]

[[package]]
name = "tokenless-helper"
version = "0.1.2"
`)

  updateCargoPackageVersion(cargoToml, '0.2.0')
  updateCargoPackageVersion(cargoLock, '0.2.0')

  const updatedToml = fs.readFileSync(cargoToml, 'utf8')
  const updatedLock = fs.readFileSync(cargoLock, 'utf8')
  assert.match(updatedToml, /\[package\]\nname = "tokenless-daemon"\nversion = "0\.2\.0"/)
  assert.match(updatedToml, /\[dependencies\]\ntokenless-helper = "0\.1\.2"/)
  assert.match(updatedLock, /^version = 4$/m)
  assert.match(updatedLock, /name = "ahash"\nversion = "0\.8\.12"/)
  assert.match(updatedLock, /name = "tokenless-daemon"\nversion = "0\.2\.0"/)
  assert.match(updatedLock, /name = "tokenless-helper"\nversion = "0\.1\.2"/)
})

test('release versioning keeps package-lock native optional dependencies coherent', (t) => {
  const fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'tokenless-release-lock-'))
  t.after(() => fs.rmSync(fixture, { recursive: true, force: true }))
  const lockPath = path.join(fixture, 'package-lock.json')
  const optionalDependencies = Object.fromEntries(nativePackages.map((packageName) => [packageName, '0.2.0']))
  const packages = {
    'packages/cli': {
      name: 'tokenless',
      version: '0.1.2',
      optionalDependencies: Object.fromEntries(nativePackages.map((packageName) => [packageName, '0.1.2'])),
    },
  }

  for (const packageName of nativePackages) {
    packages[`node_modules/${packageName}`] = {
      version: '0.1.2',
      resolved: `https://registry.npmjs.org/${packageName}/-/${packageName}-0.1.2.tgz`,
      integrity: 'sha512-stale',
      optional: true,
    }
  }

  fs.writeFileSync(lockPath, `${JSON.stringify({ lockfileVersion: 3, packages }, null, 2)}\n`)

  updatePackageLock(lockPath, { optionalDependencies }, '0.2.0')

  const lock = JSON.parse(fs.readFileSync(lockPath, 'utf8'))
  assert.equal(lock.packages['packages/cli'].version, '0.2.0')
  assert.deepEqual(lock.packages['packages/cli'].optionalDependencies, optionalDependencies)
  for (const packageName of nativePackages) {
    const entry = lock.packages[`node_modules/${packageName}`]
    assert.equal(entry.version, '0.2.0')
    assert.equal(entry.optional, true)
    assert.equal('resolved' in entry, false)
    assert.equal('integrity' in entry, false)
  }
  assert.doesNotMatch(JSON.stringify(lock), /tokenless-native-[^"]+-0\.1\.2\.tgz/)
})

function readJson(relativePath) {
  return JSON.parse(readText(relativePath))
}

function readText(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8')
}
