export const CLI_MESSAGES = {
  en: {
    agentAdmissionRetry: 'Retry this admission with --admission-ref {admissionRef}.',
    upgradeTitle: 'Tokenless upgrade', failed: 'Tokenless CLI failed.',
    agentsInstallNextStep: 'Restart Codex, open /hooks, and trust the Tokenless hook definition before expecting automatic chat and turn binding.',
    agentsInstalled: 'Tokenless is installed for normal Codex sessions. Restart Codex and trust the Tokenless hooks in /hooks.',
    agentsRemoved: 'Tokenless Codex guidance and hook handlers were removed without changing other Codex instructions or hooks.',
    agentsNotInstalled: 'Codex integration was not installed; add --install-codex to opt in.', agentsInstallHint: 'To install the optional Codex integration, rerun setup with --install-codex.',
    waitingForUser: 'Your help is needed: complete provider sign-in or verification in the visible browser. Tokenless will preserve this job and continue afterward.',
    waitingNoWindow: 'Your help is needed, but no browser window is open. Resume this same job in headed mode; do not create a replacement job.', waitingCheckpoint: 'After completing sign-in or verification, query this same job or task; Tokenless will continue from its saved checkpoint.',
    resume: 'Resume:', completed: 'Completed', failedLabel: 'Failed', waitingLabel: 'Waiting for user', usage: 'Usage:', commonOptions: 'Common options:', options: 'Options:', validCommands: 'Valid commands:', details: 'Details:', error: 'error:', none: '(none)',
    setupTitle: 'Tokenless setup', setupReadingConfig: 'Reading config', setupCheckingNpm: 'Checking npm version', setupInstallingCodex: 'Installing Tokenless Codex integration', setupProviderSignIn: 'Provider sign-in', setupChooseProviderRemoval: 'Reply with the provider numbers to remove, separated by commas. Press Enter to keep all: ', setupChoice: 'Choose [{index}]: ', setupAntiDetectPrompt: 'Use Anti-Detect mode? Tokenless will install the verified, platform-pinned CloakBrowser if needed.', setupNativeBrowserPrompt: 'Choose a browser you provide. Tokenless does not bundle or download Chrome or Brave.', setupNativeBrowserChrome: 'My Google Chrome', setupNativeBrowserBrave: 'My Brave Browser', setupCheckingNativeBrowser: 'Looking for your {browser} installation', setupNativeBrowserMissing: 'Setup finished without browser access because {browser} was not found. Provider checks were not run.', setupNativeBrowserPathNextStep: 'Before using a browser command, run: tokenless config --browser {browser} --browser-executable-path "/absolute/path/to/browser" --json',
    setupSavingConfiguration: 'Saving profile configuration', setupCheckingProvider: 'Checking {provider} sign-in', setupNpmUnavailable: 'Could not check npm latest tokenless version: {code}.', setupNpmAvailable: 'tokenless {latest} is available on npm; local CLI is {current}.', setupNpmCurrent: 'tokenless {current} is up to date with npm.', setupProviderAuthenticated: '{provider} is authenticated ({access}).', setupProviderStatus: '{provider} sign-in status: {auth}; access: {access}.', setupProviderFailed: '{provider} readiness failed: {code}.', maintenanceSkills: 'Upserting global Tokenless agent skills', maintenanceG4f: 'Installing the pinned GPT4Free provider runtime', maintenanceDaemon: 'Reconciling current Tokenless daemon', upgradePhaseNpmInstall: 'Updating global CLI', upgradePhaseResolveGlobalCli: 'Verifying installed CLI', upgradePhaseSkills: 'Refreshing agent skills', upgradePhaseRuntimeInstall: 'Updating local runtime', upgradePhaseDoctor: 'Running doctor', upgradeProgressStarted: '  - {label}...', upgradeProgressSucceeded: '  OK {label}', upgradeProgressFailed: '  X {label}{error}', upgradeCurrent: 'Tokenless {version} is up to date. Skills and local runtime are current; doctor is healthy.', upgradeChanged: 'Tokenless upgraded from {before} to {after}. Skills and local runtime are current; doctor is healthy.', upgradeIncomplete: 'Tokenless upgrade did not complete. Rerun tokenless upgrade for a full diagnostic.', upgradeStopped: 'Tokenless upgrade stopped at {label}{error}. Resolve that failure, then rerun tokenless upgrade.', helpPunctuation: ':', helpAdvancedUsageTitle: 'Advanced Usage',
    helpUsage: 'Usage', helpAdvancedUsage: 'Advanced usage', helpCanonical: 'Canonical commands for everyday workflows.', helpAdvanced: 'Less common commands for detailed control and maintenance.', helpRun: 'Run', helpRunDescription: 'Send work through a visible AI provider.', helpSetup: 'Setup', helpSetupDescription: 'Get Tokenless ready for first use.', helpProfile: 'Profile', helpProfileDescription: 'Manage browser profiles and their sign-in sessions.', helpProvider: 'Provider', helpProviderDescription: 'Manage AI providers and their visible controls.', helpOther: 'Other', helpOtherDescription: 'Use miscellaneous maintenance and help commands.', helpAdvancedRunDescription: 'Customize, inspect, resume, or cancel jobs.', helpAdvancedSetupDescription: 'Connect native Chrome and configure Tokenless profiles.', helpAdvancedProfileDescription: 'Manage logical Tokenless profiles.', helpAdvancedProviderDescription: 'Use low-level actions and provider-specific controls.', helpAdvancedOtherDescription: 'Inspect or update persistent Tokenless configuration.', helpShortOptions: 'Short options:', helpProfileOption: 'Select a managed browser profile.', helpProviderOption: 'Select an AI provider.', helpVerboseOption: 'Show live status and diagnostic details.', helpReference: 'Command reference:', dashboardTitle: 'Tokenless local console', dashboardSkip: 'Skip to content', dashboardLanguage: 'Language', setupApiProxyPrompt: 'Accept OpenAI/Anthropic-compatible API traffic on the local daemon?', setupApiProxyModePrompt: 'How should proxied API turns map onto provider conversations?', setupApiProxyNewConversation: 'Start a new provider conversation for every request', setupApiProxyContinueConversation: 'Reuse one provider conversation per caller thread',
    agentRunSummary: 'Agent run {runId}: {status}.', agentApprovalCall: 'Approval required for {tool}. Arguments: {arguments}. Digest: {digest}.', agentApprovalResume: 'Approve with: tokenless agent resume --run-id {runId} --approve {callId}:{digest}', agentAuthenticationCall: 'Authentication is required for {tool}. Arguments: {arguments}.', agentAuthenticationResume: 'After completing authentication, run: tokenless agent resume --run-id {runId} --auth-completed {callId}:{digest}', agentInputNeed: 'Input required for {needId}: {prompt}', agentInputResume: 'Answer with: tokenless agent resume --run-id {runId} --answer {needId}=<json>', agentProviderResume: 'After completing the provider handoff, run: tokenless agent resume --run-id {runId} --provider-ready',
  },
  'zh-CN': {
    agentAdmissionRetry: '请使用 --admission-ref {admissionRef} 重试同一 admission。',
    upgradeTitle: 'Tokenless 升级', failed: 'Tokenless CLI 执行失败。',
    agentsInstallNextStep: '请重启 Codex，打开 /hooks，并信任 Tokenless hook definition，之后才能使用自动 chat 和 turn 绑定。',
    agentsInstalled: 'Tokenless 已安装到普通 Codex sessions。请重启 Codex，并在 /hooks 中信任 Tokenless hooks。',
    agentsRemoved: 'Tokenless Codex guidance 和 hook handlers 已移除；其他 Codex instructions 与 hooks 未被修改。',
    agentsNotInstalled: '未安装 Codex 集成；如需启用，请添加 --install-codex。', agentsInstallHint: '如需安装可选的 Codex 集成，请使用 --install-codex 重新运行 setup。',
    waitingForUser: '需要你的协助：请在可见浏览器中完成 provider 登录或验证。Tokenless 会保留当前 job，完成后继续。',
    waitingNoWindow: '需要你的协助，但当前没有打开浏览器窗口。请以 headed mode 恢复同一个 job，不要创建替代 job。', waitingCheckpoint: '完成登录或验证后，请查询同一个 job 或 task；Tokenless 会从已保存的 checkpoint 继续。',
    resume: '恢复：', completed: '已完成', failedLabel: '失败', waitingLabel: '等待用户', usage: '用法：', commonOptions: '通用选项：', options: '选项：', validCommands: '可用命令：', details: '详情：', error: '错误：', none: '（无）',
    setupTitle: 'Tokenless 设置', setupReadingConfig: '读取配置', setupCheckingNpm: '检查 npm 版本', setupInstallingCodex: '安装 Tokenless Codex 集成', setupProviderSignIn: 'Provider 登录状态', setupChooseProviderRemoval: '请输入要移除的 provider 编号，多个编号用逗号分隔。直接回车保留全部：', setupChoice: '选择 [{index}]：', setupAntiDetectPrompt: '是否使用 Anti-Detect mode？如有需要，Tokenless 会安装经过验证、按平台固定版本的 CloakBrowser。', setupNativeBrowserPrompt: '请选择由你提供的浏览器。Tokenless 不会 bundle 或下载 Chrome/Brave。', setupNativeBrowserChrome: '我的 Google Chrome', setupNativeBrowserBrave: '我的 Brave Browser', setupCheckingNativeBrowser: '查找你的 {browser} 安装', setupNativeBrowserMissing: 'Setup 已完成，但因为找不到 {browser}，目前不能使用浏览器；provider 检查尚未运行。', setupNativeBrowserPathNextStep: '使用 browser command 前请运行：tokenless config --browser {browser} --browser-executable-path "/浏览器的绝对路径" --json',
    setupSavingConfiguration: '保存 profile 配置', setupCheckingProvider: '检查 {provider} 登录状态', setupNpmUnavailable: '无法检查 npm 最新 tokenless 版本：{code}。', setupNpmAvailable: 'npm 上已有 tokenless {latest}；本地 CLI 为 {current}。', setupNpmCurrent: 'tokenless {current} 已是 npm 最新版本。', setupProviderAuthenticated: '{provider} 已认证（{access}）。', setupProviderStatus: '{provider} 登录状态：{auth}；访问权限：{access}。', setupProviderFailed: '{provider} 就绪状态检查失败：{code}。', maintenanceSkills: '更新全局 Tokenless agent skills', maintenanceG4f: '安装固定版本的 GPT4Free provider runtime', maintenanceDaemon: '协调当前 Tokenless daemon', upgradePhaseNpmInstall: '更新全局 CLI', upgradePhaseResolveGlobalCli: '验证已安装的 CLI', upgradePhaseSkills: '刷新 agent skills', upgradePhaseRuntimeInstall: '更新本地 runtime', upgradePhaseDoctor: '运行 doctor', upgradeProgressStarted: '  - {label}…', upgradeProgressSucceeded: '  OK {label}', upgradeProgressFailed: '  X {label}{error}', upgradeCurrent: 'Tokenless {version} 已是最新版本。Skills 和本地 runtime 均已就绪；doctor 状态健康。', upgradeChanged: 'Tokenless 已从 {before} 升级到 {after}。Skills 和本地 runtime 均已就绪；doctor 状态健康。', upgradeIncomplete: 'Tokenless 升级未完成。请重新运行 tokenless upgrade 查看完整诊断。', upgradeStopped: 'Tokenless 升级在 {label}{error} 停止。解决该失败后，重新运行 tokenless upgrade。', helpPunctuation: '：', helpAdvancedUsageTitle: '高级用法',
    helpUsage: '用法', helpAdvancedUsage: '高级用法', helpCanonical: '日常工作流的常用命令。', helpAdvanced: '用于精细控制和维护的进阶命令。', helpRun: '运行', helpRunDescription: '通过可见的 AI provider 执行任务。', helpSetup: '设置', helpSetupDescription: '完成 Tokenless 的首次使用设置。', helpProfile: 'Profile', helpProfileDescription: '管理浏览器 profile 及其登录 session。', helpProvider: 'Provider', helpProviderDescription: '管理 AI provider 及其可见控件。', helpOther: '其他', helpOtherDescription: '使用其他维护和帮助命令。', helpAdvancedRunDescription: '自定义、检查、恢复或取消 job。', helpAdvancedSetupDescription: '连接 native Chrome 并配置 Tokenless profile。', helpAdvancedProfileDescription: '管理逻辑 Tokenless profile。', helpAdvancedProviderDescription: '使用底层 action 和 provider 专属控件。', helpAdvancedOtherDescription: '检查或更新持久化 Tokenless 配置。', helpShortOptions: '短选项：', helpProfileOption: '选择托管浏览器 profile。', helpProviderOption: '选择 AI provider。', helpVerboseOption: '显示实时状态和诊断详情。', helpReference: '命令参考：', dashboardTitle: 'Tokenless 本地控制台', dashboardSkip: '跳到主要内容', dashboardLanguage: '语言', setupApiProxyPrompt: '是否让本地 daemon 接受 OpenAI/Anthropic 兼容的 API 流量？', setupApiProxyModePrompt: '代理的 API 请求应如何映射到 provider 会话？', setupApiProxyNewConversation: '每个请求都新建一个 provider 会话', setupApiProxyContinueConversation: '每个调用方线程复用同一个 provider 会话',
    agentRunSummary: 'Agent run {runId}：{status}。', agentApprovalCall: '{tool} 需要批准。参数：{arguments}。摘要：{digest}。', agentApprovalResume: '批准命令：tokenless agent resume --run-id {runId} --approve {callId}:{digest}', agentAuthenticationCall: '{tool} 需要完成身份验证。参数：{arguments}。', agentAuthenticationResume: '完成身份验证后运行：tokenless agent resume --run-id {runId} --auth-completed {callId}:{digest}', agentInputNeed: '{needId} 需要输入：{prompt}', agentInputResume: '回答命令：tokenless agent resume --run-id {runId} --answer {needId}=<json>', agentProviderResume: '完成 provider 交接后运行：tokenless agent resume --run-id {runId} --provider-ready',
  },
} as const

export type CliMessageKey = keyof typeof CLI_MESSAGES.en

export const CLI_ERROR_MESSAGES = {
  en: { invalidOption: '{command} does not accept option{plural}: {options}.' },
  'zh-CN': { invalidOption: '{command} 不接受选项：{options}。' },
} as const

export type CliErrorMessageKey = keyof typeof CLI_ERROR_MESSAGES.en

export { ERROR_SUMMARIES_ZH } from '#tokenless-protocol/localized-errors.js'
export type { LocalizedErrorCode } from '#tokenless-protocol/localized-errors.js'
