export const ERROR_SUMMARIES_ZH = {
  browser_page_busy: '页面正在使用或保留中，不能替换。',
  browser_page_unavailable: '工作标签页不可用，已保留。',
  github_copilot_control_unsupported: '这些控制仅适用于 GitHub Copilot。',
  github_copilot_choice_unavailable: '当前 GitHub Copilot 模式或账户无法使用请求的选项。',
  github_copilot_choice_not_selected: 'GitHub Copilot 未在页面上选中请求的选项。',
  github_copilot_agent_image_required: 'GitHub Copilot Agent 接受 PNG、JPEG、GIF 和 WebP 图片；文本及代码附件请使用 Ask。',
  invalid_github_copilot_mode: '--copilot-mode 必须是 ask 或 agent。',
  invalid_github_copilot_repository: '--copilot-repo 必须是 owner/repo。',
  github_copilot_agent_mode_required: 'GitHub Copilot agent.execute 需要 --copilot-mode agent。',
  github_copilot_repository_mismatch: '指定 --workspace-mode 时，--copilot-repo 和 --project-name 必须指向同一 repository。',
  github_copilot_repository_required: '启动 GitHub Copilot Agent 前需要选择 repository。',
  github_copilot_repository_fixed: '已有 Agent session 的 repository 固定；请选择新 session 来更换 repository。',
  github_copilot_repository_unavailable: '当前 GitHub Copilot 模式无法使用这个 repository。',
  github_copilot_mode_unavailable: '未找到 GitHub Copilot 的可见模式选项。',
  github_copilot_usage_unavailable: 'GitHub Copilot 页面未显示预期的 AI credits 用量。',
  github_copilot_message_usage_unavailable: 'GitHub Copilot 页面未显示预期的单条回复 token 用量。',
  github_copilot_agent_ambiguous: '同时出现多个新的 GitHub Copilot Agent session，无法确定本次任务。',
  github_copilot_agent_session_unavailable: 'GitHub Copilot 未显示本次新提交的 Agent session。',
  github_copilot_agent_steps_unavailable: 'GitHub Copilot 未显示已完成 Agent 任务的工具步骤。',
  upgrade_confirmation_required: '更新将重启 Tokenless API daemon，活跃任务可能中断。请添加 --yes 确认。',
  upgrade_activation_failed: '新版 Tokenless API 启动或验证失败。未执行自动回滚；请检查本地 daemon 状态。',
  macos_app_release_asset_unavailable: '此 release 尚未提供对应的 macOS 安装包和 SHA-256 校验文件，暂时无法更新。',
  macos_app_release_unavailable: '暂时无法读取 macOS release，请检查网络后手动重新检查。',
  database_schema_too_new: '数据库版本高于当前安装包支持的版本；请先升级 Tokenless API。',
  database_schema_incompatible: '数据库结构不兼容，migration 已停止。',
  database_schema_invalid: '数据库 schema 版本无效，无法执行 migration。',
  playwright_active_browser_configuration_mismatch: '请求与当前浏览器配置不匹配；浏览器及其中运行的任务已保留。',
  featurebench_option_invalid: 'FeatureBench option 无效。',
  featurebench_option_required: '缺少必需的 FeatureBench option。',
  featurebench_subcommand_invalid: '请使用有效的 FeatureBench subcommand。',
  agent_command_invalid: '请使用 `tokenless agent run|read|resume|cancel`。',
  agent_context_identity_conflict: 'Agent context 中的 identity 相互冲突。',
  agent_context_incomplete: 'Agent context 不完整。',
  agent_context_task_conflict: 'Agent context 中的 task identity 相互冲突。',
  agent_integration_unsupported: '不支持该 agent 集成。',
  agent_intervention_invalid: 'Harness intervention 格式无效。',
  agent_intervention_required: '恢复 Harness run 时必须提供批准、身份验证完成或回答。',
  agent_mcp_config_invalid: 'MCP 配置必须是仅包含本地 stdio server 的有效 JSON。',
  agent_run_id_required: '请提供有效的 Harness --run-id。',
  agents_subcommand_required: '请指定 agents 子命令。',
  agents_command_invalid: '请使用有效的 agents 子命令。',
  attachment_action_unsupported: '当前 action 不支持 attachment。',
  attachment_bundle_invalid: 'Attachment bundle 无效。',
  arena_agent_capability_combination_unavailable: 'Arena agent.execute 不能与 comparison、Image 或 Code outcome 组合。',
  arena_agent_continuation_unavailable: '在 Arena Agent continuation 单独完成真实验证前，agent.execute 不能与 conversation.continue 组合。',
  arena_agent_explicit_target_unavailable: 'Arena agent.execute 会选择固定的 /agent surface，不接受 --target-url。',
  arena_agent_file_upload_unavailable: '在 Arena Agent attachment lifecycle 单独完成真实验证前，agent.execute 不支持文件输入。',
  arena_agent_model_control_unavailable: 'Arena agent.execute 不能与 --model 组合。',
  arena_agent_citations_not_visible: 'Arena Agent 没有显示与当前回答关联的 HTTPS citations。',
  arena_agent_response_ambiguous: 'Arena Agent 当前 run 没有显示唯一的终态回答容器。',
  arena_agent_response_too_large: 'Arena Agent 回答超过完整可见输出边界。',
  arena_agent_steps_not_visible: 'Arena Agent 当前 run 没有显示有界的 tool steps。',
  arena_agent_steps_too_large: 'Arena Agent tool-step 输出超过完整可见步骤边界。',
  arena_agent_surface_control_unavailable: 'Arena Agent 是独立 surface，不能与 --arena-mode 或 --arena-modality 组合。',
  arena_comparison_continuation_unavailable: '在 comparison continuation 单独完成真实验证前，model.compare 不能与 conversation.continue 组合。',
  arena_comparison_model_control_unavailable: 'Arena model.compare 不能与 --model 组合。',
  arena_comparison_modality_unavailable: 'Arena model.compare 当前仅支持 --arena-modality text。',
  arena_comparison_mode_unavailable: 'Arena model.compare 需要 --arena-mode battle 或 --arena-mode side-by-side。',
  arena_control_unsupported: 'Arena surface control 仅支持 Arena provider。',
  grok_imagine_unsupported: 'Grok Imagine control 仅支持 Grok provider。',
  gemini_image_unsupported: 'Gemini Images control 仅支持 Gemini provider。',
  arena_code_continuation_unavailable: '在 Arena Code continuation 单独完成真实验证前，网站生成不能与 conversation.continue 组合。',
  arena_code_file_content_count_invalid: 'Arena Code 当前文件必须只显示一个代码内容面板。',
  arena_code_model_control_unavailable: 'Arena 网站生成不能与 --model 组合。',
  arena_code_modality_unavailable: 'Arena 网站生成需要 --arena-modality code。',
  arena_code_mode_unavailable: 'Arena 网站生成需要 --arena-mode direct。',
  arena_image_continuation_unavailable: '在 Arena Image continuation 单独完成真实验证前，图片生成与编辑不能与 conversation.continue 组合。',
  arena_image_model_control_unavailable: 'Arena 图片生成与编辑不能与 --model 组合。',
  arena_image_modality_unavailable: 'Arena 图片生成与编辑需要 --arena-modality image。',
  arena_image_mode_unavailable: 'Arena 图片生成与编辑需要 --arena-mode direct。',
  meta_image_asset_collision: 'Meta AI 图片 asset 路径已存在，未覆盖已有文件。',
  meta_image_asset_identity_invalid: 'Meta AI 图片 asset identity 无效。',
  meta_image_asset_metadata_mismatch: 'Meta AI 图片落盘 metadata 与实际 bytes 不一致。',
  meta_image_asset_root_invalid: 'Meta AI 图片 asset 路径无效或越出 Tokenless asset root。',
  meta_image_asset_unavailable: 'Meta AI 图片生成需要可用的 Tokenless asset root。',
  meta_image_bytes_invalid: 'Meta AI 返回的图片 bytes 不是可解码的 PNG、JPEG 或 WebP。',
  meta_image_bytes_too_large: 'Meta AI 返回的图片超过 Tokenless asset 大小限制。',
  meta_image_download_failed: '无法通过当前 browser session 下载 Meta AI 图片 bytes。',
  meta_image_media_type_invalid: 'Meta AI 图片返回了无效的 media type。',
  meta_image_media_type_mismatch: 'Meta AI 图片 media type 与实际 bytes 不一致。',
  meta_image_metadata_mismatch: 'Meta AI 可见图片尺寸与下载 bytes 不一致。',
  meta_image_url_invalid: 'Meta AI 图片 URL 必须是可见的 HTTPS URL。',
  gemini_image_asset_collision: 'Gemini 图片 asset 路径已存在，未覆盖已有文件。',
  gemini_image_asset_identity_invalid: 'Gemini 图片 asset identity 无效。',
  gemini_image_asset_metadata_mismatch: 'Gemini 图片落盘 metadata 与实际 bytes 不一致。',
  gemini_image_asset_root_invalid: 'Gemini 图片 asset 路径无效或越出 Tokenless asset root。',
  gemini_image_asset_unavailable: 'Gemini Images 图片生成需要可用的 Tokenless asset root。',
  gemini_image_bytes_invalid: 'Gemini Images 返回的图片 bytes 不是可解码的 PNG、JPEG 或 WebP。',
  gemini_image_bytes_too_large: 'Gemini Images 返回的图片超过 Tokenless asset 大小限制。',
  gemini_image_download_failed: '无法从当前 Gemini browser page 读取图片 bytes。',
  gemini_image_media_type_invalid: 'Gemini Images 图片返回了无效的 media type。',
  gemini_image_media_type_mismatch: 'Gemini Images 图片 media type 与实际 bytes 不一致。',
  gemini_image_metadata_mismatch: 'Gemini Images 可见图片尺寸与读取 bytes 不一致。',
  gemini_image_url_invalid: 'Gemini Images 图片 URL 必须是当前页面的 blob URL。',
  gemini_image_response_not_visible: 'Gemini Images 当前 response 没有可见的图片结果。',
  gemini_image_response_unstable: 'Gemini Images 尚未显示稳定完成的图片结果。',
  gemini_image_response_cursor_missing: 'Gemini Images 缺少提交前的当前页面 blob baseline。',
  meta_response_unstable: 'Meta AI 尚未显示稳定完成的图片结果。',
  chatgpt_chat_surface_not_selected: '无法选中 ChatGPT 的 Chat 模式。',
  chatgpt_chat_surface_not_visible: '未显示 ChatGPT 的 Chat 输入框控制菜单。',
  chatgpt_work_surface_unsupported: '当前对话使用 ChatGPT Work，请打开新的 Chat 对话。',
  chatgpt_image_asset_collision: 'ChatGPT 图片 asset 路径已存在，未覆盖已有文件。',
  chatgpt_image_asset_identity_invalid: 'ChatGPT 图片 asset identity 无效。',
  chatgpt_image_asset_metadata_mismatch: 'ChatGPT 图片落盘 metadata 与实际 bytes 不一致。',
  chatgpt_image_asset_root_invalid: 'ChatGPT 图片 asset 路径无效或越出 Tokenless asset root。',
  chatgpt_image_asset_unavailable: 'ChatGPT 图片生成需要可用的 Tokenless asset root。',
  chatgpt_image_bytes_invalid: 'ChatGPT 返回的图片 bytes 不是可解码的 PNG、JPEG 或 WebP。',
  chatgpt_image_bytes_too_large: 'ChatGPT 返回的图片超过 Tokenless asset 大小限制。',
  chatgpt_image_download_failed: '无法通过当前 browser session 下载 ChatGPT 图片 bytes。',
  chatgpt_image_media_type_invalid: 'ChatGPT 图片返回了无效的 media type。',
  chatgpt_image_media_type_mismatch: 'ChatGPT 图片 media type 与实际 bytes 不一致。',
  chatgpt_image_metadata_mismatch: 'ChatGPT 可见图片尺寸与下载 bytes 不一致。',
  chatgpt_image_url_invalid: 'ChatGPT 图片 URL 必须是可见的 HTTPS URL。',
  chatgpt_image_response_not_visible: 'ChatGPT 当前 assistant turn 没有可见的图片结果。',
  chatgpt_image_response_unstable: 'ChatGPT 尚未显示稳定完成的图片结果。',
  arena_video_capability_combination_unavailable: 'Arena video.generation 不能与 comparison、Search、Image、Code 或 Agent outcome 组合。',
  arena_video_continuation_unavailable: '在 Arena Video continuation 单独完成真实验证前，video.generation 不能与 conversation.continue 组合。',
  arena_video_explicit_target_unavailable: 'Arena video.generation 会选择固定的 /video surface，不接受 --target-url。',
  arena_video_file_upload_unavailable: '在 Arena image-to-video lifecycle 单独完成真实验证前，video.generation 不支持文件输入。',
  arena_video_model_control_unavailable: 'Arena video.generation 不能与 --model 组合。',
  arena_video_response_ambiguous: 'Arena Video 当前 assistant turn 没有显示恰好两个唯一视频产物。',
  arena_video_response_too_large: 'Arena Video artifact references 超过完整可见输出边界。',
  arena_video_surface_control_unavailable: 'Arena Video 是独立的 Battle-only surface，不能与 --arena-mode 或 --arena-modality 组合。',
  arena_search_continuation_unavailable: '在 Arena Search continuation 单独完成真实验证前，Search 不能与 conversation.continue 组合。',
  arena_search_modality_unavailable: 'Arena search.web 与 response.citations 需要 --arena-modality search。',
  arena_search_mode_unavailable: 'Arena search.web 与 response.citations 需要 --arena-mode direct。',
  browser_runtime_repair_download_conflict: 'Browser runtime repair 不能与禁用下载同时使用。',
  browser_executable_path_conflict: '不能同时使用 --browser-executable-path 与 --clear-browser-executable-path。',
  browser_executable_path_requires_system_browser: '只有 native Chrome 或 Brave setup 可以使用 --browser-executable-path。',
  browser_executable_not_found: '找不到或无法验证 browser executable。请配置所选 Chrome/Brave 的绝对 executable path。',
  browser_runtime_selection_required: '请选择至少一个 browser runtime。',
  capabilities_command_invalid: '请使用 `tokenless capabilities list`。',
  capabilities_subcommand_required: '请指定 capabilities 子命令。',
  chatgpt_controls_unsupported: '当前 ChatGPT controls 操作不受支持。',
  codex_home_requires_install: '--codex-home 必须与 --install-codex 同时使用。',
  controls_unsupported_for_action: '当前 action 不支持 provider controls。',
  daemon_command_invalid: '请使用有效的 daemon 子命令。',
  daemon_request_too_large: 'Daemon request 过大。',
  deepseek_capability_combination_unavailable: '当前 DeepSeek capability 组合不可用。',
  deepseek_control_unsupported: '该 DeepSeek control 不受支持。',
  deepseek_deepthink_required: '该操作需要启用 DeepThink。',
  deepseek_file_unavailable_in_expert: 'DeepSeek Expert mode 不支持文件上传；请使用 Instant 或 Vision。',
  deepseek_image_requires_vision: 'DeepSeek 图片输入需要 Vision mode。',
  deepseek_search_required: '该操作需要启用 DeepSeek search。',
  deepseek_search_requires_instant: 'DeepSeek search 需要 Instant mode。',
  doubao_control_unsupported: '该 Doubao control 不受支持。',
  duplicate_effort: '--effort 与 --thinking-effort 只能选择一个。',
  duplicate_prompt: '--prompt 与 --prompt-file 只能选择一个。',
  duplicate_workspace_instructions: '--project-instructions 与 --project-instructions-file 只能选择一个。',
  incomplete_agent_recipient: 'Agent recipient 信息不完整。',
  invalid_agent_kind: 'Agent kind 无效。',
  invalid_agent_session_id: 'Agent session id 无效。',
  invalid_argument: '命令参数无效。',
  invalid_arena_modality: '--arena-modality 必须是 text、search、image 或 code。',
  invalid_arena_mode: '--arena-mode 必须是 battle、side-by-side 或 direct。',
  invalid_browser: '浏览器选择无效。',
  invalid_browser_visibility: '浏览器可见性无效。',
  invalid_chat_surface: 'ChatGPT 当前仅支持 chat surface。',
  invalid_deepseek_mode: 'DeepSeek mode 必须是 Instant、Expert 或 Vision。',
  invalid_deepseek_toggle: 'DeepSeek toggle 必须是 on 或 off。',
  invalid_doubao_mode: 'Doubao mode 无效。',
  invalid_doubao_skill: 'Doubao skill 无效。',
  invalid_effort: 'Effort label 无效。',
  invalid_fields: '请求包含不受支持的字段。',
  invalid_kimi_search: '--kimi-search 必须是 auto 或 off。',
  invalid_kimi_choice: 'Kimi choice 无效。',
  invalid_kimi_plugin: 'Kimi plugin 无效。',
  invalid_kimi_skill: 'Kimi skill 无效。',
  invalid_language: '语言必须是 en 或 zh-CN。',
  invalid_limits_command: '请使用有效的 limits 子命令。',
  invalid_model: 'Model label 无效。',
  invalid_project_instructions: 'Project instructions 无效。',
  invalid_qwen_mode: 'Qwen mode 无效。',
  invalid_qwen_mode_variant: 'Qwen mode variant 无效。',
  invalid_task_capability: 'Task capability 无效。',
  invalid_workspace_instructions: 'Workspace instructions 无效。',
  invalid_workspace_name: 'Workspace name 无效。',
  invalid_option: '命令选项无效。',
  invalid_savings_command: '请使用有效的 savings 子命令。',
  invalid_timeout: 'Timeout 必须是有效的正整数。',
  invalid_visible_provider_action: 'Visible provider action 无效。',
  invalid_workspace_mode: '--workspace-mode 必须是 auto、native 或 conversation。',
  job_cancel_failed: '取消 job 失败。',
  job_interrupted: 'Job 已中断。',
  kimi_control_unsupported: '该 Kimi control 不受支持。',
  long_running_requires_wait: 'Long-running capability 不能与 --no-wait 同时使用。',
  missing_argument_value: '命令参数缺少值。',
  missing_visible_action_arena_surface: '请同时提供 --arena-mode 与 --arena-modality。',
  missing_job_id: '请提供 --job-id。',
  missing_prompt: '请提供 --prompt 或 --prompt-file。',
  missing_provider_control: '请提供至少一个 provider control。',
  missing_task_id: '请提供 --task-id。',
  missing_visible_action_deepseek_deepthink: '请提供 --deepseek-deepthink。',
  missing_visible_action_deepseek_mode: '请提供 --deepseek-mode。',
  missing_visible_action_deepseek_search: '请提供 --deepseek-search。',
  missing_visible_action_doubao_mode: '请提供 --doubao-mode。',
  missing_visible_action_doubao_skill: '请提供 --doubao-skill。',
  missing_visible_action_effort: '请提供 --effort。',
  missing_visible_action_file: '请至少提供一个 --attach-file。',
  missing_visible_action_kimi_choice: '请提供必需的 Kimi choice。',
  missing_visible_action_kimi_search: '请提供 --kimi-search。',
  missing_visible_action_model: '请提供 --model。',
  missing_visible_action_qwen_mode: '请提供 --qwen-mode。',
  missing_workspace_name: '请提供 --project-name。',
  native_chrome_executable_unsupported: '原生 Chrome 会自动发现正在运行的稳定版，不接受 executable path。',
  native_chrome_headless_unsupported: '原生 Chrome 仅支持 headed mode。',
  native_chrome_required: 'Tokenless 原生模式仅支持正在运行的 Google Chrome 或 Brave Browser。',
  native_browser_not_installed: '找不到所选的 Chrome 或 Brave。请在实际使用浏览器前配置 browser executable path。',
  output_savings_clear_confirmation_required: '清除输出节省历史前需要明确确认。',
  output_savings_uninstall_confirmation_required: '移除输出节省运行时前需要明确确认。',
  profile_clear_runner_unsafe: 'Playwright runner identity 未验证，不能清除 profile。',
  profile_clear_target_required: '--profile 与 --all 必须且只能选择一个。',
  profile_config_scope_invalid: 'Profile config scope 无效。',
  profile_config_scope_required: '请指定 profile config scope。',
  profile_color_invalid: 'Profile color 必须使用 #RRGGBB 格式。',
  profile_delete_confirmation_required: '移除 profile 前需要 --confirm-delete。',
  profile_managed_browser_required: '该 profile 需要 managed browser。',
  profile_not_configured: '找不到该 profile 的配置。',
  profile_not_found: '找不到该 profile。',
  profile_open_provider_required: '使用 --target-url 打开 profile 时必须提供 --provider。',
  profiles_command_invalid: '请使用有效的 profiles 子命令。',
  menubar_command_invalid: '请使用 `tokenless menubar status`。',
  conversation_continue_mapping_required: '继续对话需要当前 task 已存在精确的 provider conversation mapping。',
  conversation_continue_target_mismatch: '继续对话的 target 必须与当前 task 的精确 provider conversation mapping 一致。',
  conversation_continue_task_identity_required: '继续对话需要稳定的 task identity。',
  conversation_continue_workspace_required: '继续对话需要 --workspace-mode conversation。',
  provider_mapping_invalid: 'Provider mapping 无效。',
  provider_unavailable: '当前 profile 没有可用 provider；请重新运行 setup 或完成 provider 登录。',
  provider_not_enabled: '请先为该 profile 启用 provider。',
  provider_not_supported: '该 provider 暂不受支持。',
  provider_required: '请提供 --provider。',
  provider_selection_invalid: '选择类型必须是 model 或 effort。',
  qwen_mode_unsupported: '该 Qwen mode action 只能用于 Qwen provider。',
  qwen_mode_variant_requires_mode: '--qwen-mode-variant 需要同时提供 --qwen-mode。',
  setup_anti_detect_browser_conflict: '--anti-detect 只能与 --browser cloak 同时使用。',
  setup_browser_unsupported: 'Setup 仅支持 native Chrome、native Brave 或显式 CloakBrowser。',
  setup_profile_name_unavailable: '选定的 profile 名称不可用。',
  setup_profile_not_ready: '选定的 profile 尚未就绪。',
  setup_profile_runtime_mismatch: 'Profile 与选定的 browser runtime 不匹配。',
  setup_provider_required: 'Setup 至少需要一个 provider。',
  setup_selection_invalid: 'Setup 选项无效。',
  invalid_api_proxy_command: '用法：tokenless api-proxy <status|enable|disable> --json',
  task_capability_action_unsupported: '该 action 不支持请求的 task capability。',
  task_capability_combination_unsupported: '请求的 task capability 组合不受支持。',
  task_capability_input_required: '请求的 task capability 缺少必需输入。',
  task_capability_route_unavailable: '没有可用的 provider capability route。',
  task_state_not_found: '找不到 task state。',
  task_state_profile_not_found: '找不到 task 对应的 profile。',
  tokenless_config_invalid: 'Tokenless 配置无效；请检查 language、profile 和 browser 设置。',
  tokenless_config_unreadable: '无法读取 Tokenless 配置。',
  too_many_attachments: '一次 visible request 最多支持 100 个 attachment。',
  dashboard_body_too_large: '请求内容过大。',
  dashboard_csrf_rejected: '请求安全令牌无效。',
  dashboard_host_rejected: '请求 Host 不受允许。',
  dashboard_json_invalid: '请求内容必须是有效的 JSON object。',
  dashboard_origin_rejected: '请求来源不受允许。',
  dashboard_request_failed: 'Dashboard 请求失败。',
  dashboard_route_not_found: '找不到请求的 Dashboard 接口。',
  dashboard_session_required: '请重新打开本地 Dashboard 以建立新会话。',
  unknown_command: '未知的 Tokenless 命令。',
  unknown_argument: '未知的 Tokenless 参数。',
  limits_command_invalid: '请使用有效的 limits 子命令。',
  savings_command_invalid: '请使用有效的 savings 子命令。',
  unsupported_provider: '该 provider 不受支持。',
  unsupported_visible_action: '该 visible action 不受支持。',
  visible_action_payload_option: '该 option 不适用于当前 visible action。',
} as const

export type LocalizedErrorCode = keyof typeof ERROR_SUMMARIES_ZH
