export const DAEMON_PROCESS_SCHEMA_ID = 'tokenless.daemon-process.v1' as const
export const DAEMON_SNAPSHOT_SCHEMA_ID = 'tokenless.daemon-snapshot.v1' as const
export const DAEMON_TASK_STATE_SCHEMA_ID = 'tokenless.daemon-task-state.v1' as const
export const MANAGED_PLAYWRIGHT_JOB_SCHEMA_ID_V3 = 'tokenless.playwright.job.v3' as const
export const RELEASE_PENDING_SCHEMA_ID = 'tokenless.release-pending.v1' as const
export const RUNNER_CHECKPOINT_SCHEMA_ID_V2 = 'tokenless.playwright.runner-checkpoint.v2' as const
export const TOKENLESS_CONFIG_SCHEMA_ID = 'tokenless.config.v1' as const
export const USER_HANDOVER_SCHEMA_ID = 'tokenless.playwright.user-handover.v1' as const
export const VISIBLE_ACTION_SCHEMA_ID_V3 = 'tokenless.playwright.visible-action.v3' as const
export const VISIBLE_ATTACHMENT_SCHEMA_ID = 'tokenless.visible-attachment.v1' as const
export const MANAGED_PLAYWRIGHT_JOB_SCHEMA_ID = MANAGED_PLAYWRIGHT_JOB_SCHEMA_ID_V3
export const RUNNER_CHECKPOINT_SCHEMA_ID = RUNNER_CHECKPOINT_SCHEMA_ID_V2
export const VISIBLE_ACTION_SCHEMA_ID = VISIBLE_ACTION_SCHEMA_ID_V3
