import type { JsonRecord } from '../types.js'
import type { ViewContext } from '../view-context.js'
import { jobRows, pageHeader } from './shared.js'

const statuses = ['queued', 'claimed', 'running', 'waiting_for_user', 'succeeded', 'failed', 'canceled', 'timed_out']

export function renderJobs(context: ViewContext) {
  return `<section class="page">${pageHeader(context, context.t('durableJobs'), context.t('jobsLede'))}<div class="filters"><select id="job-status"><option value="">${context.esc(context.t('allStatuses'))}</option>${statuses.map((value) => `<option>${value}</option>`).join('')}</select><select id="job-provider"><option value="">${context.esc(context.t('allProviders'))}</option>${context.snapshot.providers.map((provider: JsonRecord) => `<option value="${context.esc(provider.id)}">${context.esc(provider.label)}</option>`).join('')}</select><select id="job-profile"><option value="">${context.esc(context.t('allProfiles'))}</option>${context.snapshot.profiles.map((profile: JsonRecord) => `<option value="${context.esc(profile.id)}">${context.esc(profile.label)}</option>`).join('')}</select><input id="job-search" type="search" placeholder="${context.esc(context.t('searchJobs'))}"></div><div class="panel" id="job-list">${jobRows(context, context.snapshot.jobs)}</div><dialog id="detail-dialog"></dialog></section>`
}

export function renderJobDetail(context: ViewContext, job: JsonRecord) {
  const actions = `${job.profileSlug && job.provider ? `<button class="button" data-job-provider-open>${context.esc(context.t('openBrowser'))}</button>` : ''}${job.status === 'waiting_for_user' ? `<button class="button primary" data-job-action="resume">${context.esc(context.t('resume'))}</button>` : ['queued', 'claimed', 'running'].includes(job.status) ? `<button class="button danger" data-job-action="cancel">${context.esc(context.t('cancel'))}</button>` : ''}`
  return `<div class="dialog-head"><h2>${context.esc(job.taskId ?? job.jobId)}</h2><button class="button" data-close-detail>${context.esc(context.t('cancel'))}</button></div><div class="dialog-body"><p><span class="status ${context.esc(job.status)}">${context.esc(job.status)}</span></p><p class="secondary">${context.esc(context.t('created'))}: ${context.esc(context.time(job.createdAt))}<br>${context.esc(context.t('updated'))}: ${context.esc(context.time(job.updatedAt))}<br>${context.esc(job.profileSlug ?? job.profileId ?? '')} · ${context.esc(job.provider ?? '')}${job.agent ? `<br>${context.esc(job.agent.kind)} · ${context.esc(job.agent.sessionId)}` : ''}</p><div class="button-row">${actions}</div><section class="section"><h3>${context.esc(context.t('result'))}</h3><pre class="code-block">${context.esc(JSON.stringify(job.result, null, 2))}</pre></section><section class="section"><h3>${context.esc(context.t('error'))}</h3><pre class="code-block">${context.esc(JSON.stringify(job.error ?? job.blocker, null, 2))}</pre></section><section class="section"><h3>${context.esc(context.t('attempts'))}</h3><pre class="code-block">${context.esc(JSON.stringify(job.providerAttempts, null, 2))}</pre></section></div>`
}
